"%dev":
  quarkus:
    log:
      category:
        "com.besza":
          level: DEBUG
    datasource:
      username: postgres
      password: secret
  app:
    scraper:
      cron: "0 * * * * ?"
    database:
      host: localhost

quarkus:
  package:
    type: uber-jar
  datasource:
    db-kind: postgresql
    username: ${PGUSER}
    password: ${PGPASSWORD}
    jdbc:
      url: jdbc:postgresql://${app.database.host}:5432/postgres?reWriteBatchedInserts=true
  hibernate-orm:
    jdbc:
      timezone: UTC
      statement-batch-size: 30
  flyway:
    migrate-at-start: true
    validate-on-migrate: true
    baseline-on-migrate: true
    baseline-version: 202101021844
  resteasy:
    gzip:
      enabled: true
      max-input: 10M

app:
  database:
    host: ${PGHOST}
  scraper:
    cron: "0 30 22 * * ?"
